### ISSUE TITLE
The app has a too techy / misleading description

### ISSUE THREAD

**Issue by manuq** [flathub/com.github.debauchee.barrier#1]
I would expect the title to be: "Barrier - Share mouse and keyboard over the local network", similar to [Teleport](https://flathub.org/apps/details/com.frac_tion.teleport) "Share files over the local network".

The description is also too techy "Barrier is KVM software forked from Symless's (...)". I would expect to find the features first, like "shares the clipboard too". And leave the paragraph about the app's history for the end.

**Comment by AdrianKoshka** [comment]
Fair enough I suppose. I'll change it when I get around to it.

**Comment by AdrianKoshka** [comment]
Hope this fixes the issue for you.

**Comment by manuq** [comment]
@AdrianKoshka thank you!
