### ISSUE TITLE
ignores system theme and no icon in taskbar

### ISSUE THREAD

**Issue by IvoryJam** [flathub/com.github.debauchee.barrier#17]
Expected Behavior: On start Barrier will start themed like the system, with the icon in the taskbar showing status.

Current Behavior: Starts as light themed (I'm using Arc Dark installed with flatpak) icon not showing in dash-to-panel, slower to start

Currently rolling back to commit 68e72e6381c2bc579be7572487be6652b32d54fa resolves all of this

System Info:
OS: Ubuntu 20.04 LTS x86_64 
Kernel: 5.4.0-42-generic

**Comment by AdrianKoshka** [comment]
This should be fixed soon, I hope.

**Comment by IvoryJam** [comment]
Issue has been resolved by update
