### ISSUE TITLE
New release reverted fix for system tray icon

### ISSUE THREAD

**Issue by ahayzen** [flathub/com.github.debauchee.barrier#18]
The new release 2.3.3 https://github.com/flathub/com.github.debauchee.barrier/commit/3d7f82da19d5c1823ab9d23c5e2db57d179be10b reverted the fix for slow startup and no tray icon https://github.com/flathub/com.github.debauchee.barrier/commit/8fc2ad2cfc221ef53d407e094db810e5007af74d

Are you able to reapply this change ?

**Comment by AdrianKoshka** [comment]
Aaah, yep, I see what happened now!
