### ISSUE TITLE
Upstream develop has requested to take over maintainership role

### ISSUE THREAD

**Issue by AdrianKoshka** [flathub/com.github.debauchee.barrier#21]
@TingPing as I'm not as closely affiliated with the project anymore, an upstream developer (@shymega) has requested to take over as package maintainer of this flatpak. I'm entirely willing to do this, and would appreciate some help in the process of making them package maintainer.

**Comment by TingPing** [comment]
I have invited them to the repo.

**Comment by shymega** [comment]
Received and accepted invitation. Thanks.
