### ISSUE TITLE
[Question]: How to auto start barrier client in Linux distro

### ISSUE THREAD

**Issue by byteshiva** [flathub/com.github.debauchee.barrier#24]
How to auto start client in linux distro?

Can someone let me know if the below command will work

`
flatpak run --command="barrierc -f --no-tray --debug INFO --name desktop --enable-crypto [192.168.9.3]:24800" com.github.debauchee.barrier
`

**Comment by shymega** [comment]
This has been documented in an issue in the main Barrier repository, as a systemd service. I can't recall the exact issue ID on my mobile though.. but yes, that command might work. Not sure. Have you tried it?

**Comment by byteshiva** [comment]
Yes I did, Here are the errors

```
$flatpak run --command="barrier -f --no-tray --debug INFO --name desktop --enable-crypto [192.168.9.3]:24800" com.github.debauchee.barrier

bwrap: execvp barrier -f --no-tray --debug INFO --name desktop --enable-crypto [192.168.9.3]:24800: No such file or directory```
```

```
$flatpak run --command="barrierc -f --no-tray --debug INFO --name desktop --enable-crypto [192.168.9.3]:24800" com.github.debauchee.barrier

bwrap: execvp barrierc -f --no-tray --debug INFO --name desktop --enable-crypto [192.168.9.3]:24800: No such file or directory
```

referred https://github.com/debauchee/barrier/issues/441

**Comment by shymega** [comment]
Regarding the first command - that needs to be `barriers`, as you're starting a server.

I'm still confused as to your approach - it seems that the executable of Barrier you're calling doesn't exist; which seems odd, because the Flatpak has worked for other people...

**Comment by byteshiva** [comment]
> Regarding the first command - that needs to be `barriers`, as you're starting a server.
> 
> I'm still confused as to your approach - it seems that the executable of Barrier you're calling doesn't exist; which seems odd, because the Flatpak has worked for other people...

Same error for `barriers` too
```
$flatpak run --command="barriers -f --no-tray --debug INFO --name desktop --enable-crypto [192.168.9.3]:24800" com.github.debauchee.barrier

bwrap: execvp barriers -f --no-tray --debug INFO --name desktop --enable-crypto [192.168.9.3]:24800: No such file or directory```
```

**Comment by shymega** [comment]
You need to use these commands:

Client:
`flatpak run --command="barrierc" com.github.debauchee.barrier "-f --no-tray --debug INFO --name desktop --enable-crypto [192.168.9.3]:24800"`

Server:
`flatpak run --command="barriers" com.github.debauchee.barrier "-f --no-tray --debug INFO --name desktop --enable-crypto [192.168.9.3]:24800"`

**Comment by shymega** [comment]
Although, you have an unexpected argument on the `barriers` command. Reopening until you confirm that you have fixed it.

**Comment by byteshiva** [comment]
Client Side:
`
 flatpak run --command="barrierc" com.github.debauchee.barrier "-f --no-tray --debug INFO --name desktop --enable-crypto [192.168.9.3]:24800"
`
The client command ran without throwing error but it didn't get connected  with server. I may again be missing something here. I'll try this again and keep you updated


Server Side: 


![image](https://user-images.githubusercontent.com/10637299/101395668-47a16c80-38f0-11eb-943e-2ddb1117c178.png)

**Comment by shymega** [comment]
I thought you wanted to run `barriers` as a Flatpak? Or do you want to run the GUI? You can only really do one or the other - IIRC.

**Comment by byteshiva** [comment]
> I thought you wanted to run barriers as a Flatpak? Or do you want to run the GUI? You can only really do one or the other - IIRC.

Eventually I'd go for `barriers`(server) as a background service. But for convenience and easy debug purpose I choose GUI using Flatpak at one machine and `barrierc`(client) at the other machine.

I'll try running `barriers`(server) and `barrierc`(client) on different machines and keep you updated.

**Comment by shymega** [comment]
Right. I don't think it'll make much difference. You setup the screens on the GUI? Make sure client and server have different names. That's critiical.

**Comment by byteshiva** [comment]
> Although, you have an unexpected argument on the `barriers` command. Reopening until you confirm that you have fixed it.

Now I'm passing the right argument but it throws below error. How do I pass arguments using flatpak?
```
flatpak run --command="barriers" com.github.debauchee.barrier "-f --no-tray --debug INFO --name server-machine --enable-crypto -c /etc/barriers.conf --address :24800"`

barriers: unrecognized option `-f --no-tray --debug INFO --name server-machine --enable-crypto -c /etc/barriers.conf --address :24800'

Try `barriers --help' for more information.
```

**Comment by ak65234** [comment]
> barriers: unrecognized option `-f --no-tray --debug INFO --name server-machine --enable-crypto -c /etc/barriers.conf --address :24800'

Try removing the quotes surrounding the arguments you're trying to pass to `barriers`:

`flatpak run --command="barriers" com.github.debauchee.barrier -f --no-tray --debug INFO --name server-machine --enable-crypto -c /etc/barriers.conf --address :24800`

See [Flatpak Reference](https://docs.flatpak.org/en/latest/flatpak-command-reference.html#flatpak-run)

**Comment by byteshiva** [comment]
> > barriers: unrecognized option `-f --no-tray --debug INFO --name server-machine --enable-crypto -c /etc/barriers.conf --address :24800'
> 
> Try removing the quotes surrounding the arguments you're trying to pass to `barriers`:
> 
> `flatpak run --command="barriers" com.github.debauchee.barrier -f --no-tray --debug INFO --name server-machine --enable-crypto -c /etc/barriers.conf --address :24800`
> 
> See [Flatpak Reference](https://docs.flatpak.org/en/latest/flatpak-command-reference.html#flatpak-run)

Thanks @shymega , @ak65234 ,

It works!. 
Now I've to make it run as background services for both barrier **server** and **client**( run service before login screen). 

Here are the steps for any future reference

**Step 1:**

**SERVER** 
Run `barriers` (s - Server), Important note, need to specify the configuration file.

`flatpak run --command="barriers" com.github.debauchee.barrier -f --no-tray --debug INFO --name server-machine --enable-crypto -c /etc/barriers.conf --address :24800`

**Step 2:**

**CLIENT**
Run the `barrierc` ( c - client) at the client computers.

In my case `192.168.3.9` is the server address, it'll vary based on network connections

```
/usr/bin/flatpak run  --command="barrierc"  com.github.debauchee.barrier  -f --no-tray --debug INFO --name client-desktop --enable-crypto [192.168.3.9]:24800`
```

**Server side Logs:**
```
flatpak run --command="barriers" com.github.debauchee.barrier -f --no-tray --debug INFO --name server-desktop --enable-crypto -c /etc/barriers.conf --address :24800
started server (IPv4/IPv6), waiting for clients
[2020-12-09T13:07:07] INFO: OpenSSL 1.1.1g  21 Apr 2020
[2020-12-09T13:07:07] INFO: accepted secure socket
[2020-12-09T13:07:07] INFO: TLS_AES_256_GCM_SHA384  TLSv1.3 Kx=any      Au=any  Enc=AESGCM(256) Mac=AEAD

[2020-12-09T13:07:07] NOTE: accepted client connection
[2020-12-09T13:07:07] NOTE: client "client-desktop" has connected
[2020-12-09T13:07:21] INFO: switch from "server-machine" to "client-desktop" at 0,184
[2020-12-09T13:07:21] INFO: leaving screen
[2020-12-09T13:07:21] INFO: screen "server-desktop" updated clipboard 0
[2020-12-09T13:07:21] INFO: screen "server-desktop" updated clipboard 1
[2020-12-09T13:07:22] INFO: switch from "client-desktop" to "server-desktop" at 2558,295
[2020-12-09T13:07:22] INFO: entering screen
[2020-12-09T13:07:23] INFO: switch from "server-desktop" to "client-desktop" at 0,525
[2020-12-09T13:07:23] INFO: leaving screen
[2020-12-09T13:07:24] INFO: switch from "client-desktop" to "server-desktop" at 2545,334
[2020-12-09T13:07:24] INFO: entering screen
[2020-12-09T13:07:28] INFO: switch from "server-desktop" to "client-desktop" at 0,983
[2020-12-09T13:07:28] INFO: leaving screen
[2020-12-09T13:07:29] INFO: switch from "client-desktop" to "server-desktop" at 2554,1416
[2020-12-09T13:07:29] INFO: entering screen
[2020-12-09T13:07:29] INFO: switch from "server-desktop" to "client-desktop" at 0,1075
[2020-12-09T13:07:29] INFO: leaving screen
[2020-12-09T13:07:30] INFO: switch from "client-desktop" to "server-desktop" at 2558,1434
[2020-12-09T13:07:30] INFO: entering screen
[2020-12-09T13:11:49] INFO: switch from "server-desktop" to "client-desktop" at 0,697
[2020-12-09T13:11:49] INFO: leaving screen
[2020-12-09T13:11:49] INFO: screen "server-desktop" updated clipboard 0
[2020-12-09T13:11:49] INFO: screen "server-desktop" updated clipboard 1
[2020-12-09T13:12:03] INFO: screen "client-desktop" grabbed clipboard 1 from "server-desktop"
[2020-12-09T13:12:05] INFO: screen "client-desktop" grabbed clipboard 0 from "server-desktop"
[2020-12-09T13:12:07] INFO: switch from "client-desktop" to "server-desktop" at 2544,924
[2020-12-09T13:12:07] INFO: entering screen
[2020-12-09T13:12:07] INFO: screen "client-desktop" updated clipboard 0
[2020-12-09T13:12:10] INFO: screen "server-desktop" grabbed clipboard 1 from "client-desktop"
[2020-12-09T13:12:42] INFO: screen "server-desktop" grabbed clipboard 0 from "client-desktop"
```

Notes:
Make sure the computers are connected to networks, Wifi et al.

FAQs:
How to add in `startup and sessions` on Linux OS

![image](https://user-images.githubusercontent.com/10637299/101601853-2ab98600-3a23-11eb-9463-89d0ae347606.png)

**Comment by thehefi** [comment]
My flatpak auto starts:

Version 2.3.1-snapshot-58d8f020 / Peppermint10 on old 32bit laptop:
Added following to Settings / System / Startup & Default Applications / Autostart / Manual autostarted applications:
/usr/bin/flatpak run --branch=stable --arch=i386 --command=barrier com.github.debauchee.barrier -c barrier.conf

Version 2.3.3-release-3395cca9 / Linux Mint 20.1 beta on 64bit Laptop:
Added to Startup programs and edited launcher like this:
/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=barrier com.github.debauchee.barrier -c barrier.conf

Just my 2cents...

**Comment by byteshiva** [comment]
> My flatpak auto starts:
> 
> Version 2.3.1-snapshot-58d8f020 / Peppermint10 on old 32bit laptop:
> Added following to Settings / System / Startup & Default Applications / Autostart / Manual autostarted applications:
> /usr/bin/flatpak run --branch=stable --arch=i386 --command=barrier com.github.debauchee.barrier -c barrier.conf
> 
> Version 2.3.3-release-3395cca9 / Linux Mint 20.1 beta on 64bit Laptop:
> Added to Startup programs and edited launcher like this:
> /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=barrier com.github.debauchee.barrier -c barrier.conf
> 
> Just my 2cents...

My next task would be to start  barrier client before login in ubuntu 20.04. 
https://github.com/debauchee/barrier/wiki/Command-Line#systemd

But somehow systemd barrier script is not getting started before login.

```
[Unit]
Description=Barrier Client daemon
After=network.target
Before=getty.target

[Service]
User=xyz
Group=xyz
ExecStart=/usr/bin/flatpak run  --command="barrierc"  com.github.debauchee.barrier  -f --no-tray --debug INFO --name client-desktop --enable-crypto [192.168.3.9]:24800
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
~                                                                               
~                                                                               
```

**Comment by shymega** [comment]
Sorry for the late reply. You need `$XDG_RUNTIME_DIR` set before you can use Flatpak - that's my understanding. Therefore, the DM (login screen) wouldn't have one associated with your user.

I will close for now, as I don't think this is within the scope of Barrier, given that it's designed to run upon logon, not before logon, where the running UID isn't of the designated user.
