### ISSUE TITLE
Roll flatpak version to 2.4.0

### ISSUE THREAD

**Issue by Aaron-von-Awesome** [flathub/com.github.debauchee.barrier#25]
Please roll the flatpak version to 2.4.0 - I couldn't find a better way to ask when this would happen or what the team timeline was, so sorry if this is already in progress!!

https://github.com/debauchee/barrier/releases/tag/v2.4.0

**Comment by shymega** [comment]
There's a clear discussions tab on the Barrier repo, that *would* have been a better place to ask. I will bump this when I get home onto my Linux machine.

**Comment by shymega** [comment]
OK, I'm looking at it now. I've bumped the AppData XML file to use the latest releases, and I'm currently building it locally.

**Comment by shymega** [comment]
OK, this might take longer than I anticipated. It seems there are a few bugs with the manifest. I'll try and finish it this week...

**Comment by shymega** [comment]
Due to long-lasting organisational issues with Barrier, I am now no longer maintaining this Flatpak -or the Snap, as I have left the `debauchee` group. I will open a new issue looking for a new maintainer.

**Comment by shymega** [comment]
#26 created. Keeping this open for a new maintainer...

**Comment by shymega** [comment]
@mikeeq Just to remind you, this needs actioning.

**Comment by mikeeq** [comment]
v2.4.0 release was published, and it's now available to download - <https://buildbot.flathub.org/#/builders/6/builds/5939>
