### ISSUE TITLE
Removal of my email address, and change email to the maintainer of this Flatpak.

### ISSUE THREAD

**Issue by shymega** [flathub/com.github.debauchee.barrier#28]
Hi,

I've been getting emails still - my bad really, I should have removed my email address from the repo before giving up maintainership - but these emails want support with Barrier, and I'm not involved with that now.

Can we change to someone else's?

Thanks.

**Comment by mikeeq** [comment]
If anything else needs changing besides [this](https://github.com/flathub/com.github.debauchee.barrier/blob/master/com.github.debauchee.barrier.appdata.xml#L59) let me know ;)
