### ISSUE TITLE
Flathub install results in 404

### ISSUE THREAD

**Issue by nightlyowli** [flathub/com.github.debauchee.barrier#30]
From Flathub trying to download gives 404.
https://dl.flathub.org/repo/appstream/com.github.debauchee.barrier.flatpakref

**Comment by shymega** [comment]
I got notified of this issue, weirdly enough, but whilst I'm here - HTTP request returns 200 now.

**Comment by nightlyowli** [comment]
Looks like it was resolved some time ago 👍
